# Generated by Django 4.1.1 on 2022-09-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('flight_number', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_class', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('flight_route', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_route_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
