# Generated by Django 4.1.1 on 2022-10-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="arrival_airport",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="arrival_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="arrival_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="carrier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="departure_airport",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="departure_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="departure_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
