# Generated by Django 4.1.1 on 2022-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_ticket_arrival_airport_ticket_arrival_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
