# Generated by Django 4.1.1 on 2022-10-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_ticket_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
