# Generated by Django 4.1.1 on 2022-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_ticket_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(blank=True, max_length=255, null=True),
        ),
    ]
